spring.application.name=Recursos# Configuración del servidor
server.address=0.0.0.0
server.port=${PORT:8080}

# Configuración de la base de datos (PostgreSQL) con Neon
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# HikariCP (optimizado)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.leak-detection-threshold=60000


# SSL es obligatorio en Render
spring.datasource.hikari.data-source-properties.sslmode=require

# Configuración de Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Otros
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Aca estan las propierties del security y del "hackeo" para mantener viva la api
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
